---
source:
  path: /your/source/path/
  codec: libx265
  crf: 18
  preset: slow
  level: '5.1'
  pixels: yuv420p
  profile: main
  audio: ac3
  arate: 384k

source2:
  path: /your/source/path2/
  codec: libx265
  crf: 22
  preset: medium
  level: '5.0'
  pixels: yuv420p
  profile: main
  audio: aac
  arate: 160k